/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textanalizer;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author luis
 */
public class InterfazServidor extends javax.swing.JFrame {
    
    public LineasText lines; //crea un text pane y le agrega su scrooll y dibuja los numeros en el panel donde se agrega
    public LineasText lines2;
    public String texto;
    public String nombrePro;
    
    
    public InterfazServidor() {
        initComponents();
        jPanel1.setLayout(new BorderLayout());
        lines =new LineasText();
        jPanel1.add(lines,BorderLayout.WEST);
        jPanel1.add(lines.scrollPane,BorderLayout.CENTER);
        jPanel2.setLayout(new BorderLayout());
        lines2= new LineasText();
        jPanel2.add(lines2,BorderLayout.WEST);
        jPanel2.add(lines2.scrollPane,BorderLayout.CENTER);
        posicionPuntero();
        consola.setText("BIENVENIDO!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        noFila = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noCol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        cargarPro = new javax.swing.JMenuItem();
        guardarPro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        analizar = new javax.swing.JMenuItem();
        subirNuve = new javax.swing.JMenuItem();
        verErrores = new javax.swing.JMenuItem();
        mTecnico = new javax.swing.JMenu();
        mUser = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Area de Edición", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Area de Formato", jPanel2);

        jScrollPane2.setViewportView(consola);

        jTabbedPane2.addTab("Consola de Salida", jScrollPane2);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jTabbedPane3.addTab("Proyectos Guardados", jScrollPane3);

        jLabel1.setText("FILA:");

        noFila.setText("0");

        jLabel3.setText("COLUMNA:");

        noCol.setText("0");

        jMenu3.setText("Inicio");

        cargarPro.setText("Cargar Proyecto");
        cargarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarProActionPerformed(evt);
            }
        });
        jMenu3.add(cargarPro);

        guardarPro.setText("Guardar Proyecto");
        guardarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProActionPerformed(evt);
            }
        });
        jMenu3.add(guardarPro);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Herramientas");

        analizar.setText("Analizar");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });
        jMenu4.add(analizar);

        subirNuve.setText("Subir a la nuve");
        jMenu4.add(subirNuve);

        verErrores.setText("Ver Errores");
        jMenu4.add(verErrores);

        jMenuBar1.add(jMenu4);

        mTecnico.setText("Acerca de");

        mUser.setText("Manual de Usuario");
        mUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserActionPerformed(evt);
            }
        });
        mTecnico.add(mUser);

        jMenuItem7.setText("Manual Tecnico");
        mTecnico.add(jMenuItem7);

        jMenuBar1.add(mTecnico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noFila)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noCol)
                        .addGap(325, 325, 325))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(noFila)
                    .addComponent(jLabel3)
                    .addComponent(noCol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarProActionPerformed
    JFileChooser filechoos = new JFileChooser();
    String ruta;
    int opcion = filechoos.showOpenDialog(this);
    if(opcion==JFileChooser.APPROVE_OPTION){
    nombrePro=filechoos.getSelectedFile().getName();
    ruta= filechoos.getSelectedFile().getPath();
    texto=leerArchivo(ruta);
    //System.out.println("El texto es: \n"+texto);
    lines.pane.setText(texto);
    if(!"".equals(texto)){
        consola.setText(consola.getText()+"\nAVISO: Archivo cargado correctamente.");
    }else{
        consola.setText(consola.getText()+"\nAVISO: No hay texto para cargar.");
    }
    }
        
    }//GEN-LAST:event_cargarProActionPerformed

    private void guardarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarProActionPerformed

    private void mUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUserActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
     
        if(!"".equals(lines.pane.getText())){
            
            Lexico lex = new Lexico(new BufferedReader( new StringReader(lines.pane.getText())));
            lex.pintar.darEstilo(lines.pane.getText());
            lines2.pane.setDocument(lex.pintar.caja2.getDocument());
            Sintactico  sint=new Sintactico(lex);
            try {                                 
                //aca se compila                   
                sint.parse();
                consola.setText(consola.getText()+"\nAVISO: Analisis realizado correctamente.");
                jTabbedPane1.setSelectedIndex(1);
            } catch (Exception ex) {
                 Logger.getLogger(InterfazServidor.class.getName()).log(Level.SEVERE, null, ex);
                 consola.setText(consola.getText()+"\nError: No se pudo realizar el analisis sintactico.");
            }
        }else{
             consola.setText(consola.getText()+"\nAVISO: No hay texto para realizar el analisis.");
        }
           
    }//GEN-LAST:event_analizarActionPerformed

    public String leerArchivo(String ruta){
        texto=""; 
        try (BufferedReader bf = new BufferedReader(new FileReader(ruta))) {
              String bflinea;
              while((bflinea=bf.readLine())!=null ){
              texto+=bflinea+"\n";
              }
                                            
          } catch (Exception e) {
              System.err.println("Lectura Incorrecta de archivo");
          }
        return  texto;
    }
    
    private void posicionPuntero(){
        lines.pane.addCaretListener(new CaretListener(){
            
            @Override
            public void caretUpdate(CaretEvent e) {
                int pos = e.getDot();
		int fila = 1, columna=0;
		int ultimalinea=-1;
		String text =lines.pane.getText().replaceAll("\r","");
				
		for(int i=0;i<pos;i++){
                    if(text.charAt(i)==10){
                        fila++;
                        ultimalinea=i;
                    }
                }
				
		columna=pos-ultimalinea;                
                noFila.setText(fila +"");
                noCol.setText(columna+"");
            }
        });
        
         lines2.pane.addCaretListener(new CaretListener(){
            
            @Override
            public void caretUpdate(CaretEvent e) {
                int pos = e.getDot();
		int fila = 1, columna=0;
		int ultimalinea=-1;
		String text =lines2.pane.getText().replaceAll("\r","");
				
		for(int i=0;i<pos;i++){
                    if(text.charAt(i)==10){
                        fila++;
                        ultimalinea=i;
                    }
                }
				
		columna=pos-ultimalinea;                
                noFila.setText(fila +"");
                noCol.setText(columna+"");
            }
        });
    }
    
    
    public void correrInterfaz(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem analizar;
    private javax.swing.JMenuItem cargarPro;
    private javax.swing.JTextPane consola;
    private javax.swing.JMenuItem guardarPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JMenu mTecnico;
    private javax.swing.JMenuItem mUser;
    private javax.swing.JLabel noCol;
    private javax.swing.JLabel noFila;
    private javax.swing.JMenuItem subirNuve;
    private javax.swing.JMenuItem verErrores;
    // End of variables declaration//GEN-END:variables
}
