/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.Cocina;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Usuario;

/**
 *
 * @author USER
 */
public class VentanaClientes extends javax.swing.JFrame implements Observer {

    private Cocina gestorListaCocina;
    private Vista vis;
    private VentanaVisualisarPedido ventanaVisualisarPedido;
    private ArrayList<Object[]> listCodigo;
    private VentanaRegistrarCliente venCliente;
    private ventanaConfirmeContraseña ventanaConfirmeContraseña;
    private boolean remover;

    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes() {
        initComponents();
        vis = new Vista();
        ventanaVisualisarPedido = new VentanaVisualisarPedido(this, true);
        venCliente = new VentanaRegistrarCliente();
        ventanaConfirmeContraseña = new ventanaConfirmeContraseña(this, true);
        remover = false;
    }

    public void setGestorListaCocina(Cocina gestorListaCocina) {
        this.gestorListaCocina = gestorListaCocina;
        setIconImage(gestorListaCocina.Icono());
        ventanaVisualisarPedido.setGestorListaCocina(gestorListaCocina);
        venCliente.setGestorListaCocina(gestorListaCocina);
        venCliente.datos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        minEditar = new javax.swing.JMenuItem();
        minRemover = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblVenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxClientes = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDomicilio = new javax.swing.JTextArea();
        lblCelular = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        minEditar.setText("Modificar");
        minEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(minEditar);

        minRemover.setText("Remover");
        minRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemoverActionPerformed(evt);
            }
        });
        jPopupMenu1.add(minRemover);

        setTitle("Clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(71, 36, 39));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Producto", "Cantidad", "Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setSelectionBackground(new java.awt.Color(71, 36, 39));
        jTable1.setSelectionForeground(new java.awt.Color(255, 153, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 69, 410, 293));

        btnCerrar.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(71, 36, 39));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(71, 36, 39));
        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 153, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        lblVenta.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblVenta.setForeground(new java.awt.Color(255, 153, 0));
        lblVenta.setText("Total Venta:");
        jPanel1.add(lblVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 374, 280, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        cbxClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cbxClientes.setForeground(new java.awt.Color(71, 36, 39));
        jPanel1.add(cbxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 210, -1));

        btnRegistrar.setBackground(new java.awt.Color(71, 36, 39));
        btnRegistrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 153, 0));
        btnRegistrar.setText("Registrar Cliente");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 398, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 153, 0));
        lblCorreo.setText("sebazeco314@gmail.com");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 285, 190, -1));

        txaDomicilio.setColumns(20);
        txaDomicilio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txaDomicilio.setForeground(new java.awt.Color(98, 50, 35));
        txaDomicilio.setRows(5);
        jScrollPane2.setViewportView(txaDomicilio);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 200, 100));

        lblCelular.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 153, 0));
        lblCelular.setText("3175469495");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 190, -1));

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 153, 0));
        lblNombre.setText("Sebastian armero");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 195, 190, -1));

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Usuario.png"))); // NOI18N
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 0, 180, 180));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(199, 93, 58));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 175, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 93, 58));
        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 93, 58));
        jLabel6.setText("Correo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 265, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 93, 58));
        jLabel8.setText("Domicilio: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 153, 0));
        lblTotal.setText("total:");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 374, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Usuario7.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 442));

        jLabel3.setForeground(new java.awt.Color(71, 36, 39));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usu0.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 230, 442));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        obtenerDatosTabla(cbxClientes.getSelectedItem().toString());
        obtenerTotal();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        venCliente.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        vis.setBan(true);
        setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vis.setBan(true);
    }//GEN-LAST:event_formWindowClosing

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();
            if (row >= 0) {
                ventanaVisualisarPedido.visualizarPedido((int) listCodigo.get(row)[0]);
                ventanaVisualisarPedido.setVisible(true);
            }
        } else {
            mostrarCliente();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void minEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minEditarActionPerformed
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            venCliente.editarClientes(jTable1.getModel().getValueAt(row, 0).toString());
            venCliente.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_minEditarActionPerformed

    private void minRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemoverActionPerformed
        remover = true;
        int n = gestorListaCocina.mensajeConfirmar("¿Seguro que desea remover este cliente?", "comfirmacion");
        if (n == 0) {
            ventanaConfirmeContraseña.setVisible(true);
        }
    }//GEN-LAST:event_minRemoverActionPerformed

    private void obtenerDatosTabla(String cliente) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        listCodigo = new ArrayList<>();

        ArrayList<Object[]> ped = gestorListaCocina.obtenerClientePedido(cliente);

        ped.stream().forEach(pedido -> {

            Cliente cli = gestorListaCocina.getListaCliente().obtenerCliente((int) pedido[0]);
            if (cli.isVigente() == true) {
                Object[] obj = new Object[2];
                obj[0] = pedido[5];
                obj[1] = pedido[0];
                listCodigo.add(obj);

                pedido[0] = cli.getNombre();
                modelo.addRow(pedido);
            }

        });
    }

    private void mostrarCliente() {
        int row = jTable1.getSelectedRow();
        Cliente cli = gestorListaCocina.getListaCliente().obtenerCliente((int) listCodigo.get(row)[1]);
        gestorListaCocina.visualizadorImagen2(lblAvatar, cli.getAvatar());
        lblNombre.setText(cli.getNombre());
        lblCelular.setText(cli.getCelular());
        lblCorreo.setText(cli.getCorreo());
        txaDomicilio.setText(cli.getDomicilio());
    }

    public void datos(Observer obs, Usuario user) {
        vis.addObserver(obs);
        ventanaConfirmeContraseña.setUsuario(user, this);
        cbxClientes.removeAllItems();
        cbxClientes.addItem("Todos");
        gestorListaCocina.getListaCliente().lisaCliente(cbxClientes);
        obtenerDatosTabla("");
        obtenerTotal();
    }

    private void obtenerTotal() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        lblVenta.setText("Venta total: " + gestorListaCocina.costoReporte(modelo, 3));
        lblTotal.setText("Total: " + modelo.getRowCount());
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean) {

            if ((boolean) arg == true && remover == true) {
                int row = jTable1.getSelectedRow();
                gestorListaCocina.getListaCliente().removerCliente(jTable1.getModel().getValueAt(row, 0).toString());
                gestorListaCocina.mensaje("Cliente removido corretamente", "remover", 1);
                remover = false;
                cbxClientes.removeAllItems();
                cbxClientes.addItem("Todos");
                gestorListaCocina.getListaCliente().lisaCliente(cbxClientes);
            }

            obtenerDatosTabla(cbxClientes.getSelectedItem().toString());
            setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVenta;
    private javax.swing.JMenuItem minEditar;
    private javax.swing.JMenuItem minRemover;
    private javax.swing.JTextArea txaDomicilio;
    // End of variables declaration//GEN-END:variables
}
