/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ListaUsuario;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import model.Usuario;

//https://www.jc-mouse.net/java/textinput-material-design visualizar para editar la interface
/**
 *
 * @author USER
 */
public class VentanaLogin extends javax.swing.JFrame implements Observer{

    private final ListaUsuario gestorListaUsuario;
    private VentanaRegistrarUsuario ventanaRegistrarUsuario;
    private VentanaPrincipal ventanaPrincipal;
    private Usuario user;
    private boolean vent;

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        ventanaRegistrarUsuario = new VentanaRegistrarUsuario();
        gestorListaUsuario = new ListaUsuario();
        ventanaRegistrarUsuario.setGestorListaUsuario(gestorListaUsuario);
        ventanaPrincipal = new VentanaPrincipal();
        setIconImage(gestorListaUsuario.Icono());
        gestorListaUsuario.rutaArchivo();
        vent = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tpwContraseña = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        lblRegistrarUser = new javax.swing.JLabel();
        lblRecCont = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 35, 14));
        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(85, 35, 14));
        txtUsuario.setSelectedTextColor(new java.awt.Color(255, 191, 154));
        txtUsuario.setSelectionColor(new java.awt.Color(85, 35, 14));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 189, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 35, 14));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        tpwContraseña.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tpwContraseña.setForeground(new java.awt.Color(85, 35, 14));
        tpwContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpwContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(tpwContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 189, -1));

        btnIniciar.setBackground(new java.awt.Color(85, 35, 14));
        btnIniciar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 191, 154));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 100, -1));

        lblRegistrarUser.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblRegistrarUser.setForeground(new java.awt.Color(85, 35, 14));
        lblRegistrarUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarUser.setText("Registrar Usuario");
        lblRegistrarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarUserMouseExited(evt);
            }
        });
        jPanel1.add(lblRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 116, -1));

        lblRecCont.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblRecCont.setForeground(new java.awt.Color(85, 35, 14));
        lblRecCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecCont.setText("¿he olvidado mi contraseña?");
        lblRecCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecContMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecContMouseExited(evt);
            }
        });
        jPanel1.add(lblRecCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 176, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pasteli1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 200, 120));

        lblPin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblPin.setForeground(new java.awt.Color(85, 35, 14));
        lblPin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPin.setText("Iniciar con pin");
        lblPin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPinMouseExited(evt);
            }
        });
        jPanel1.add(lblPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 525));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        gestorListaUsuario.consumirSinEspacio(evt);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void tpwContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpwContraseñaKeyTyped
        gestorListaUsuario.consumirSinEspacio(evt);
    }//GEN-LAST:event_tpwContraseñaKeyTyped

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciarSeccion();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lblRegistrarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarUserMouseClicked
        ventanaRegistrarUsuario.setVisible(true);
        ventanaRegistrarUsuario.observer(this);
        vent = true;
    }//GEN-LAST:event_lblRegistrarUserMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        gestorListaUsuario.ArchivarUsuario();
    }//GEN-LAST:event_formWindowClosing

    private void lblRegistrarUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarUserMouseEntered
        lblRegistrarUser.setForeground(Color.GREEN);
    }//GEN-LAST:event_lblRegistrarUserMouseEntered

    private void lblRegistrarUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarUserMouseExited
        lblRegistrarUser.setForeground(new Color(85, 35, 14));
    }//GEN-LAST:event_lblRegistrarUserMouseExited

    private void lblPinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPinMouseEntered
        lblPin.setForeground(Color.GREEN);
    }//GEN-LAST:event_lblPinMouseEntered

    private void lblPinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPinMouseExited
        lblPin.setForeground(new Color(85, 35, 14));
    }//GEN-LAST:event_lblPinMouseExited

    private void lblRecContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecContMouseEntered
        lblRecCont.setForeground(Color.GREEN);
    }//GEN-LAST:event_lblRecContMouseEntered

    private void lblRecContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecContMouseExited
        lblRecCont.setForeground(new Color(85, 35, 14));
    }//GEN-LAST:event_lblRecContMouseExited

    private void lblRecContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecContMouseClicked
        String respuesta = JOptionPane.showInputDialog(
                null,
                "Ingrese Usuario",
                JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta != null) {
            validarUsuario(respuesta);
        }
    }//GEN-LAST:event_lblRecContMouseClicked

    private void lblPinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPinMouseClicked

        String respuesta = JOptionPane.showInputDialog(
                null,
                "Digite el PIN",
                JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta != null) {
            ingresarPin(respuesta);
        }

    }//GEN-LAST:event_lblPinMouseClicked

    private void validarUsuario(String res) {
        String correo = "";
        String codigo;
        String contra;
        String respuesta = "";
        boolean ban = false;

        user = gestorListaUsuario.buscarUsuario(res);

        if (user != null) {
            int n = 0;

            for (int j = 0; j < 4; j++) {
                correo += user.getCorreo().charAt(j);
            }

            correo += "****";

            for (int i = 0; i < user.getCorreo().length(); i++) {
                if (user.getCorreo().charAt(i) == '@') {
                    n = i;
                    break;
                }
            }

            for (int j = n; j < user.getCorreo().length(); j++) {
                correo += user.getCorreo().charAt(j);
            }

            codigo = gestorListaUsuario.codigoRecuperacion(user.getCorreo());

            while (respuesta != null) {
                respuesta = JOptionPane.showInputDialog(
                        null,
                        "Ingrese el codigo Que hemos enviado al correo\n " + correo,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (respuesta != null) {
                    if (codigo.equals(respuesta)) {

                        while (respuesta != null) {
                            respuesta = JOptionPane.showInputDialog(
                                    null,
                                    "Ingrese la nueva Contraseña",
                                    JOptionPane.QUESTION_MESSAGE
                            );

                            if (respuesta != null) {

                                contra = JOptionPane.showInputDialog(
                                        null,
                                        "Comfirme la Contraseña",
                                        JOptionPane.QUESTION_MESSAGE
                                );

                                if (respuesta.equals(contra)) {
                                    gestorListaUsuario.canbiarContraseña(contra, user.getUsuario());
                                    gestorListaUsuario.mensaje("Contraseña cambiada corrrectamente", "Usuario",0);
                                    ban = true;
                                    respuesta = null;
                                } else {
                                    gestorListaUsuario.mensaje("Las contraseñas no coinciden\n ...vuelva a intentarlo", "Usuario",3);
                                }
                            }
                        }
                    }
                }
            }

            if (ban == true) {
                ingresar();
            }

        } else {
            gestorListaUsuario.mensaje("El usuario no existe", "Usuario",2);
        }

    }

    private void ingresarPin(String respuesta) {
        boolean ban = false;
        if (respuesta.length() == 6) {
            for (int i = 0; i < 6; i++) {
                if (respuesta.charAt(i) < 48 && respuesta.charAt(i) > 57) {
                    ban = true;
                    break;
                }
            }

            if (ban == false) {
                user = gestorListaUsuario.buscarUsuario(Integer.valueOf(respuesta));

                if (user != null) {
                    ingresar();
                } else {
                    gestorListaUsuario.mensaje("Usuario no encontrado", "Usuario",3);
                }
            } else {
                gestorListaUsuario.mensaje("por favor ingrese un PIN valido", "Usuario",3);
            }

        } else {
            gestorListaUsuario.mensaje("por favor Ingrese un pin de 6 digitos", "Usuario",3);
        }
    }

    private void iniciarSeccion() {
        String usuario = txtUsuario.getText();
        String contraseña = "";
        user = null;

        for (int i = 0; i < tpwContraseña.getPassword().length; i++) {
            contraseña += tpwContraseña.getPassword()[i];
        }
        
        usuario= "sebas";
        contraseña ="sebas7cr7";

        if (!usuario.equals("") && !contraseña.equals("")) {
            user = gestorListaUsuario.buscarUsuario(usuario, contraseña);

            if (user != null) {
                ingresar();
            } else {
                gestorListaUsuario.mensaje("El usuario o la contraseña" + "\n" + "pueda que esten incorretos", "Usuario",2);
            }
        } else {
            gestorListaUsuario.mensaje("Todos los campos son obligatorios", "Usuario",3);
        }
    }

    private void ingresar() {
        setVisible(false);
        ventanaPrincipal.setGestorListaUsuario(gestorListaUsuario, user);
        ventanaPrincipal.gestorArchivo(user.getArchivo(),user.getRutaArchivos());
        ventanaPrincipal.setVisible(true);
        ventanaPrincipal.observer(this);
        vent = true;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean && vent == true) {
            setVisible(true);
            vent = false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
//            javax.swing.SwingUtilities.updateComponentTreeUI(VentanaLogin.this);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblRecCont;
    private javax.swing.JLabel lblRegistrarUser;
    private javax.swing.JPasswordField tpwContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
