/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.Cocina;
import controller.Categoria;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaCategoria extends javax.swing.JFrame implements Observer {

    private Cocina gestorListaCocina;
    private Vista vis;
    private VentanaRecetas ventanaReceta;
    private boolean vent;

    /**
     * Creates new form VentanaCategoria
     */
    public VentanaCategoria() {
        initComponents();
        vis = new Vista();
        ventanaReceta = new VentanaRecetas();
        vent = false;
    }

    public void setGestorListaCocina(Cocina gestorListaCocina) {
        this.gestorListaCocina = gestorListaCocina;
        ventanaReceta.setGestorListaCocina(gestorListaCocina);
        setIconImage(gestorListaCocina.Icono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popumenu = new javax.swing.JPopupMenu();
        minRem = new javax.swing.JMenuItem();
        minRemAll = new javax.swing.JMenuItem();
        minMover = new javax.swing.JMenuItem();
        minCambiarNom = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCategoria = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        popumenu.setLabel("Opcion:");

        minRem.setText("Remover");
        minRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemActionPerformed(evt);
            }
        });
        popumenu.add(minRem);

        minRemAll.setText("Remover todo");
        minRemAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemAllActionPerformed(evt);
            }
        });
        popumenu.add(minRemAll);

        minMover.setText("Mover a");
        minMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minMoverActionPerformed(evt);
            }
        });
        popumenu.add(minMover);

        minCambiarNom.setText("Editar Categoria");
        minCambiarNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minCambiarNomActionPerformed(evt);
            }
        });
        popumenu.add(minCambiarNom);

        setTitle("Categoria");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 191, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receta", "Medida", "Costo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setComponentPopupMenu(popumenu);
        jTable1.setSelectionBackground(new java.awt.Color(98, 50, 35));
        jTable1.setSelectionForeground(new java.awt.Color(255, 191, 154));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 400));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 50, 35));
        jLabel1.setText("Categoria:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, -1, -1));

        btnCategoria.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCategoria.setForeground(new java.awt.Color(98, 50, 35));
        btnCategoria.setText("Nueva Categoria");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(98, 50, 35));
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 465, 85, -1));

        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 270, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imgFondoPrincipal.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        setVisible(false);
        vis.setBan(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        jTable1.setModel(gestorListaCocina.obtenerTablaReceta(jTable1, cbxCategoria.getSelectedIndex()));
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void minRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemActionPerformed
        int row = jTable1.getSelectedRow();

        if (row >= 0) {
            gestorListaCocina.getListaCategoria().eliminarReceta(cbxCategoria.getSelectedIndex(), row);
            jTable1.setModel(gestorListaCocina.obtenerTablaReceta(jTable1, cbxCategoria.getSelectedIndex()));
            gestorListaCocina.mensaje("Receta removida correctamente", "Categoria",1);
        }

    }//GEN-LAST:event_minRemActionPerformed

    private void minRemAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemAllActionPerformed
        gestorListaCocina.getListaCategoria().eliminarRecetaAll(cbxCategoria.getSelectedIndex());
        jTable1.setModel(gestorListaCocina.obtenerTablaReceta(jTable1, cbxCategoria.getSelectedIndex()));
        gestorListaCocina.mensaje("Recetas removidas correctamente", "Categoria",1);
    }//GEN-LAST:event_minRemAllActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        String respuesta;
        respuesta = JOptionPane.showInputDialog(
                null,
                "Escriba nombre de la Categoria",
                JOptionPane.QUESTION_MESSAGE
        );

        Categoria cocina = new Categoria();

        if (respuesta != null) {
            if (!respuesta.equals("")) {
                cocina.setCategoria(respuesta);
                gestorListaCocina.getListaCategoria().agregarCategoria(cocina);
                obtenerReceta();
                gestorListaCocina.mensaje("Categoria agregada corretamente", "Categoria",0);
            }
        }
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getButton() == 3) {
            popumenu.show(jTable1, evt.getX(), evt.getY());
        }

        if (evt.getClickCount() == 2) {
            ventanaReceta.setVisible(true);
            ventanaReceta.obtenerDatos(this);
            ventanaReceta.selecionarReceta(cbxCategoria.getSelectedIndex(), jTable1.getSelectedRow());
            vent = true;
            setVisible(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vis.setBan(true);
    }//GEN-LAST:event_formWindowClosing

    private void minMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minMoverActionPerformed
        Object[] cat = gestorListaCocina.getListaCategoria().nombreCategoria();
        Object opcion = JOptionPane.showInputDialog(
                null,
                "¿A que Categoria desea mover?",
                "Categoria",
                JOptionPane.QUESTION_MESSAGE,
                null,cat, cat[0]
        );
        
        if (opcion != null) {
            gestorListaCocina.getListaCategoria().moverReceta(
                    cbxCategoria.getSelectedIndex(),
                    jTable1.getSelectedRow(),
                    opcion+""
            );
            
            gestorListaCocina.mensaje("Receta movida corretamente", "Receta",0);
            obtenerReceta();
        }

        
    }//GEN-LAST:event_minMoverActionPerformed

    private void minCambiarNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minCambiarNomActionPerformed
        String respuesta;
        respuesta = JOptionPane.showInputDialog(
                null,
                "Escriba el nombre nuevo de la categoria "+cbxCategoria.getSelectedItem(),
                JOptionPane.QUESTION_MESSAGE
        );


        if (respuesta != null) {
            if (!respuesta.equals("")) {
                gestorListaCocina.getListaCategoria().cambiarNombreCategoria(cbxCategoria.getSelectedItem()+"",respuesta);
                gestorListaCocina.mensaje("Categoria modificada corretamente", "Categoria",0);
                obtenerReceta();
            }
        }
    }//GEN-LAST:event_minCambiarNomActionPerformed

    public void obtenerReceta() {
        cbxCategoria.removeAllItems();
        gestorListaCocina.getListaCategoria().listaBoxCategoria(cbxCategoria);
        jTable1.setModel(gestorListaCocina.obtenerTablaReceta(jTable1, 0));
    }

    public void observer(Observer ven) {
        vis.addObserver(ven);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean && vent == true) {
            setVisible(true);
            vent = false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem minCambiarNom;
    private javax.swing.JMenuItem minMover;
    private javax.swing.JMenuItem minRem;
    private javax.swing.JMenuItem minRemAll;
    private javax.swing.JPopupMenu popumenu;
    // End of variables declaration//GEN-END:variables
}
