/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.Cocina;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author USER
 */
public class VentanaRegistrarCliente extends javax.swing.JFrame implements Observer {

    private Cocina gestorListaCocina;
    private Vista vis;
    private String rutaAvatar;
    private VentanaAvatar venAvatar;
    private boolean ban;
    private String oldCliente;

    /**
     * Creates new form VentanaRegistrarCliente
     */
    public VentanaRegistrarCliente() {
        initComponents();
        vis = new Vista();
        rutaAvatar = " ";
        venAvatar = new VentanaAvatar();
        ban = false;
        oldCliente = "";
    }

    public void setGestorListaCocina(Cocina gestorListaCocina) {
        this.gestorListaCocina = gestorListaCocina;
        setIconImage(gestorListaCocina.Icono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDomicilio = new javax.swing.JTextArea();
        lblAvatar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSelecionarAvatar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Registrar Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Celular:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Domicilio: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 157, -1, -1));

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(98, 50, 35));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 31, 223, -1));

        txtCelular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(98, 50, 35));
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 73, 223, -1));

        txtCorreo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(98, 50, 35));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 115, 223, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(71, 36, 39));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(71, 36, 39));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        txaDomicilio.setColumns(20);
        txaDomicilio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txaDomicilio.setForeground(new java.awt.Color(98, 50, 35));
        txaDomicilio.setRows(5);
        jScrollPane1.setViewportView(txaDomicilio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 157, 220, 119));

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Usuario.png"))); // NOI18N
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 20, 180, 180));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("es como un traje sin");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 208, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("corbata\"");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 208, -1));

        lblSelecionarAvatar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblSelecionarAvatar.setForeground(new java.awt.Color(255, 153, 0));
        lblSelecionarAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelecionarAvatar.setText("Selecionar Avatar");
        lblSelecionarAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelecionarAvatarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSelecionarAvatarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSelecionarAvatarMouseExited(evt);
            }
        });
        jPanel1.add(lblSelecionarAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 208, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("\"Una comida sin postre");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 208, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("-Fernand Point");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 190, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Usuario7.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 208, 362));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usu1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 362));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        gestorListaCocina.consumir(evt);
    }//GEN-LAST:event_txtCelularKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String msj = validarCampos();
        if (msj.equals("")) {
            registrarCliente();
        } else {
            JOptionPane.showMessageDialog(null, msj);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vis.setBan(true);
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lblSelecionarAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelecionarAvatarMouseClicked
        venAvatar.datos(this);
        venAvatar.setVisible(true);
    }//GEN-LAST:event_lblSelecionarAvatarMouseClicked

    private void lblSelecionarAvatarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelecionarAvatarMouseEntered
        lblSelecionarAvatar.setForeground(new Color(255, 153, 153));
    }//GEN-LAST:event_lblSelecionarAvatarMouseEntered

    private void lblSelecionarAvatarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelecionarAvatarMouseExited
        lblSelecionarAvatar.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_lblSelecionarAvatarMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vis.setBan(true);
    }//GEN-LAST:event_formWindowClosing

    private void registrarCliente() {
        boolean ver = gestorListaCocina.getListaCliente().verificarCliente(txtNombre.getText());

        if (ver == false || (!oldCliente.equals("") && (ver == false || oldCliente.equals(txtNombre.getText())))) {
            Cliente cli = new Cliente();

            cli.setNombre(txtNombre.getText());
            cli.setCelular(txtCelular.getText());
            cli.setCorreo(txtCorreo.getText());
            cli.setDomicilio(txaDomicilio.getText());
            cli.setAvatar(rutaAvatar);

            if (ban == false) {
                gestorListaCocina.getListaCliente().agregarCliente(cli);
                gestorListaCocina.mensaje("Cliente agregado corretamente", "Cliente", 0);
            } else {
                gestorListaCocina.getListaCliente().editarCliente(cli,oldCliente);
                gestorListaCocina.mensaje("Cliente modificado corretamente", "Cliente", 0);
            }

            setVisible(false);
            vis.setBan(false);
        }else{
            gestorListaCocina.mensaje("El cliente "+txtNombre.getText()+" ya existe!", "Cliente", 2);
        }

    }

    private String validarCampos() {
        String msj = "";

        if (txtNombre.getText().equals("")) {
            return "El campo Nombre es obligatorio";
        }

        if (txtCelular.getText().equals("")) {
            return "El campo Celular es obligatorio";
        }

        if (txtCorreo.getText().equals("")) {
            return "El campo Correo es obligatorio";
        } else {
            Pattern pattern = Pattern
                    .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

            // El email a validar
            String email = txtCorreo.getText();

            Matcher mather = pattern.matcher(email);

            if (mather.find() != true) {
                return "El email ingresado es inválido.";
            }
        }

        if (txaDomicilio.getText().equals("")) {
            return "El campo Domicilio es obligatorio";
        }

        return msj;
    }

    public void datos(Observer obs) {
        vis.addObserver(obs);
    }

    public void editarClientes(String nombre) {
        oldCliente = nombre;
        Cliente cli = gestorListaCocina.getListaCliente().obtenerCliente(nombre);
        txtNombre.setText(cli.getNombre());
        txtCelular.setText(cli.getCelular());
        txtCorreo.setText(cli.getCorreo());
        txaDomicilio.setText(cli.getDomicilio());
        rutaAvatar = cli.getAvatar();
        gestorListaCocina.visualizadorImagen2(lblAvatar, cli.getAvatar());
        ban = true;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean) {
            setVisible(true);
        } else if (arg instanceof String) {
            rutaAvatar = (String) arg;
            System.out.println("ruta: " + rutaAvatar);
            gestorListaCocina.visualizadorImagen2(lblAvatar, rutaAvatar);
            setVisible(true);
        }

    }

    public void pruebaCliente() {
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Julia", "julia@gmail.com", "3110108970", "Obrero", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Dario", "dario@gmail.com", "3209870023", "Ciudadela", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Stiven", "estiven@gmail.com", "3019874536", "Ciudadela", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Ana", "ana@gmail.com", "3189970087", "El Progreso", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Pedro", "pedro@gmail.com", "3201112299", "Florida", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Maria", "maria@gmail.com", "3224443333", "El morro", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Juan", "juan@gmail.com", "3105557788", "El Bajito", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Mario", "mario@gmail.com", "312452212", "Puente las flores", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Dilan", "dilan@gmail.com", "310901012", "Puente Humberto manzi", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Pablo", "pablo@gmail.com", "320455215", "Villalola", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Roberto", "roberto@gmail.com", "3178889966", "Morrito", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Diego", "diego@gmail.com", "315455512", "Carbonera", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Antonia", "antonia@gmail.com", "3148956798", "La playa", 0));
        gestorListaCocina.getListaCliente().agregarCliente(new Cliente("Karen", "karen@gmail.com", "3126547891", "Independencia", 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblSelecionarAvatar;
    private javax.swing.JTextArea txaDomicilio;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
