/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.Cocina;
import java.io.File;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Receta;

/**
 *
 * @author USER
 */
public class VentanaRecetas extends javax.swing.JFrame implements Observer {

    private Cocina gestorListaCocina;
    private VentanaRegistrarReceta ventana;
    private boolean vent;
    private Vista vis;
    private VentanaVisualisarProducto ven;

    /**
     * Creates new form VentanaEditarEliminarReceta
     */
    public VentanaRecetas() {
        initComponents();
        vent = false;
        vis = new Vista();
        ven = new VentanaVisualisarProducto(this, true);
    }

    public void setGestorListaCocina(Cocina gestorListaCocina) {
        this.gestorListaCocina = gestorListaCocina;
        setIconImage(gestorListaCocina.Icono());
        ven.setGestorListaCocina(gestorListaCocina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxCategoria = new javax.swing.JComboBox<>();
        cbxReceta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaPanel = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        lblBase = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Recetas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 191, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxCategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cbxCategoria.setForeground(new java.awt.Color(98, 50, 35));
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 20, 160, -1));

        cbxReceta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cbxReceta.setForeground(new java.awt.Color(98, 50, 35));
        cbxReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecetaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 180, -1));

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(98, 50, 35));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Productos", "Cantidad", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(98, 50, 35));
        jTable1.setSelectionForeground(new java.awt.Color(255, 191, 154));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(85);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 200));

        txaPanel.setEditable(false);
        txaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 50, 35)), "Preparacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(98, 50, 35))); // NOI18N
        txaPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txaPanel.setForeground(new java.awt.Color(98, 50, 35));
        txaPanel.setSelectedTextColor(new java.awt.Color(255, 191, 154));
        txaPanel.setSelectionColor(new java.awt.Color(98, 50, 35));
        jScrollPane2.setViewportView(txaPanel);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 540, 180));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 50, 35));
        jLabel2.setText("Categoria:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 22, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(98, 50, 35));
        jLabel3.setText("Receta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 22, -1, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 200, 200));

        lblCosto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(98, 50, 35));
        lblCosto.setText("Costo Total: ");
        jPanel1.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 210, -1));

        lblTipo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(98, 50, 35));
        lblTipo.setText("Tipo: ");
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 100, -1));

        btnEditar.setBackground(new java.awt.Color(98, 50, 35));
        btnEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 191, 154));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 80, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 50, 35));
        jLabel1.setText("Medida muestra de: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        txtMedida.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtMedida.setForeground(new java.awt.Color(98, 50, 35));
        txtMedida.setText("1");
        txtMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedidaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 285, 70, -1));

        lblBase.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblBase.setForeground(new java.awt.Color(98, 50, 35));
        lblBase.setText("Medida base:");
        jPanel1.add(lblBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 120, -1));

        btnExportar.setBackground(new java.awt.Color(98, 50, 35));
        btnExportar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(255, 191, 154));
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 90, -1));

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(98, 50, 35));
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 85, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imgFondoPrincipal.png"))); // NOI18N
        jLabel5.setPreferredSize(null);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        cbxReceta.removeAllItems();
        gestorListaCocina.getListaCategoria().listaBoxReceta(cbxReceta, cbxCategoria.getSelectedIndex());
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void cbxRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecetaActionPerformed
        if (cbxReceta.getSelectedIndex() >= 0) {
            obtenerReceta();
        }
    }//GEN-LAST:event_cbxRecetaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ventana = new VentanaRegistrarReceta();
        ventana.setGestorListaCocina(gestorListaCocina);
        ventana.llenarcbx(this);
        ventana.editarReceta(cbxCategoria.getSelectedIndex(), cbxReceta.getSelectedIndex());
        ventana.setVisible(true);
        setVisible(false);
        vent = true;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtMedidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedidaKeyTyped
        gestorListaCocina.consumir(evt, txtMedida.getText());
    }//GEN-LAST:event_txtMedidaKeyTyped

    private void txtMedidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedidaKeyReleased
        if (!txtMedida.getText().equals("")) {
            int cat = cbxCategoria.getSelectedIndex();
            int rec = cbxReceta.getSelectedIndex();
            double can = Double.valueOf(txtMedida.getText().replace(",", "."));
            jTable1.setModel(gestorListaCocina.obtenerTablaRecetaProductos(
                    jTable1, cat, rec, can)
            );
            obtenerDatosReceta(cat, rec, can);
        }

    }//GEN-LAST:event_txtMedidaKeyReleased

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        String ruta;

        int ventanaYesNotCancel = JOptionPane.showConfirmDialog(null,
                "¿Seguro Que quieres Exportar" + cbxReceta.getSelectedItem().toString() + "?", "Receta",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (ventanaYesNotCancel == 0) {
            JFileChooser jfile = new JFileChooser();
            int resultado = jfile.showSaveDialog(jfile);

            if (resultado != JFileChooser.CANCEL_OPTION) {
                File fileName = jfile.getSelectedFile();
                ruta = fileName.getAbsolutePath() + ".rxc";
                System.out.println("ruta: " + ruta);
                gestorListaCocina.exportarReceta(cbxReceta.getSelectedItem().toString(), ruta);
            }
        }


    }//GEN-LAST:event_btnExportarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vis.setBan(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        setVisible(false);
        vis.setBan(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();
            if (row >= 0) {
                ven.visualizarProducto(jTable1.getValueAt(row, 0) + "",false);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void obtenerDatos(Observer ven) {
        vis.addObserver(ven);
        cbxCategoria.removeAllItems();
        gestorListaCocina.getListaCategoria().listaBoxCategoria(cbxCategoria);
        cbxCategoria.setSelectedIndex(0);
        obtenerReceta();
    }

    private void obtenerReceta() {
        int cat = cbxCategoria.getSelectedIndex();
        int rec = cbxReceta.getSelectedIndex();

        Receta receta = gestorListaCocina.getListaCategoria().obtenerRecet(cat, rec);
        txtMedida.setText(receta.getCantidad() + "");

        txaPanel.setText("");
        jTable1.setModel(gestorListaCocina.obtenerTablaRecetaProductos(jTable1, cat, rec, receta.getCantidad()));

        obtenerDatosReceta(cat, rec, receta.getCantidad());
    }

    private void obtenerDatosReceta(int cat, int rec, double cantidad) {
        Object[] rece = gestorListaCocina.obtenerDatosReceta(cat, rec, cantidad);
        lblBase.setText("Medida base: " + rece[0]);
        lblImage = gestorListaCocina.visualizadorImagen(lblImage, (String) rece[1]);
        lblCosto.setText("Costo total: " + rece[2]);
        lblTipo.setText("Tipo: " + rece[3]);
        txaPanel.setText(rece[4] + "");
        gestorListaCocina.formatoJtexPanel(txaPanel);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean && vent == true) {
            setVisible(true);
            vent = false;
            obtenerReceta();
        }
    }

    public void selecionarReceta(int idxCat, int idxRec) {
        cbxCategoria.setSelectedIndex(idxCat);
        cbxReceta.setSelectedIndex(idxRec);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRecetas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRecetas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRecetas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRecetas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRecetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxReceta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextPane txaPanel;
    private javax.swing.JTextField txtMedida;
    // End of variables declaration//GEN-END:variables

}
