/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.Cocina;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.VentanaPrincipal;
import model.Producto;
import model.Usuario;

/**
 *
 * @author USER
 */
public class VentanaProductos extends javax.swing.JFrame implements Observer {

    private Cocina gestorListaCocina;
    private String rutaFile;
    private boolean ban;
    private Vista vis;
    private VentanaVisualisarProducto ven;
    private ventanaConfirmeContraseña venConfirmeContraseña;
    private boolean cambios;
    private boolean removerAll;

    /**
     * Creates new form VentanaRegistrarProductos
     */
    public VentanaProductos() {
        initComponents();
        rutaFile = "";
        gestorListaCocina = new Cocina();
        ban = false;
        vis = new Vista();
        ven = new VentanaVisualisarProducto(this, true);
        cambios = false;
        removerAll = false;
        venConfirmeContraseña = new ventanaConfirmeContraseña(this, true);
    }

    public void setGestorListaCocina(Cocina gestorListaCocina) {
        this.gestorListaCocina = gestorListaCocina;
        setIconImage(gestorListaCocina.Icono());
        ven.setGestorListaCocina(gestorListaCocina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popumenu = new javax.swing.JPopupMenu();
        minRem = new javax.swing.JMenuItem();
        minRemAll = new javax.swing.JMenuItem();
        minEditar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        popumenu.setLabel("Opcion:");

        minRem.setText("Remover");
        minRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemActionPerformed(evt);
            }
        });
        popumenu.add(minRem);

        minRemAll.setText("Remover todo");
        minRemAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemAllActionPerformed(evt);
            }
        });
        popumenu.add(minRemAll);

        minEditar.setText("Modificar");
        minEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minEditarActionPerformed(evt);
            }
        });
        popumenu.add(minEditar);

        setTitle("Producto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 191, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(98, 50, 35));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Medida", "Precio", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setSelectionBackground(new java.awt.Color(98, 50, 35));
        jTable1.setSelectionForeground(new java.awt.Color(255, 191, 154));
        jTable1.add(popumenu);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 490, 250));

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(98, 50, 35));
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 505, 85, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 50, 35)), "Añadir Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(98, 50, 35))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 50, 35));
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtProducto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(98, 50, 35));
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 173, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(98, 50, 35));
        jLabel3.setText("Medida:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(98, 50, 35));
        jLabel5.setText("Gramos/Unidad");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 97, -1, -1));

        txtMedida.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtMedida.setForeground(new java.awt.Color(98, 50, 35));
        txtMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedidaKeyTyped(evt);
            }
        });
        jPanel2.add(txtMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 173, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 50, 35));
        jLabel4.setText("Precio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 135, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(98, 50, 35));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 173, -1));

        btnAdd.setBackground(new java.awt.Color(98, 50, 35));
        btnAdd.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 191, 154));
        btnAdd.setText("Guardar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, -1));

        btnCancelar.setBackground(new java.awt.Color(102, 204, 255));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(98, 50, 35));
        btnCancelar.setText("Limpiar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, -1));

        lblImagen.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(98, 50, 35));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("Click para subir imagen");
        lblImagen.setToolTipText("");
        lblImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });
        jPanel2.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 200, 200));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 490, 230));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imgFondo1.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        gestorListaCocina.consumir(evt, txtPrecio.getText());
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtMedidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedidaKeyTyped
        evt = gestorListaCocina.consumir(evt, txtMedida.getText());
    }//GEN-LAST:event_txtMedidaKeyTyped

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
        if (txtProducto.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtProductoKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!txtProducto.getText().equals("") && !txtMedida.getText().equals("") && !txtPrecio.getText().equals("")) {
            if (ban == true) {
                modificar();
            } else {
                guardarProductos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor, llena todas las casillas");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        setVisible(false);
        vis.setBan(true);
        if (cambios == true) {
            gestorListaCocina.cargarInventario();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void minRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemActionPerformed
        int not = gestorListaCocina.mensajeConfirmar("¿Seguro que quieres eliminar este producto?", "Comfirmar eliminacion");
        if (not == 0) {
            venConfirmeContraseña.setVisible(true);
        }
    }//GEN-LAST:event_minRemActionPerformed

    private void minRemAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemAllActionPerformed
        int not = gestorListaCocina.mensajeConfirmar("¿Seguro que quieres eliminar todos los producto?", "Comfirmar eliminacion");
        if (not == 0) {
            venConfirmeContraseña.setVisible(true);
        }
    }//GEN-LAST:event_minRemAllActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getButton() == 3) {
            popumenu.show(jTable1, evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) {
            visualizarImagen();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void minEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minEditarActionPerformed
        btnAdd.setText("Modificar");
        jTable1.setEnabled(false);
        editarProducto();
        ban = true;
    }//GEN-LAST:event_minEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (ban == true) {
            jPanel2.setBorder(
                    javax.swing.BorderFactory.createTitledBorder(
                            javax.swing.BorderFactory.createLineBorder(
                                    new java.awt.Color(98, 50, 35)), "Añadir Producto",
                            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                            javax.swing.border.TitledBorder.DEFAULT_POSITION,
                            new java.awt.Font("Dialog", 1, 12),
                            new java.awt.Color(98, 50, 35)
                    )
            );

            ban = false;
            jTable1.setEnabled(true);
            btnAdd.setText("Guardar");
            txtMedida.setText("");
            txtPrecio.setText("");
            txtProducto.setText("");
            btnCancelar.setText("Limpiar pantalla");
            btnCancelar.setBackground(new Color(102, 204, 255));
            btnCancelar.setForeground(new Color(98, 50, 35));
        } else {
            txtMedida.setText("");
            txtPrecio.setText("");
            txtProducto.setText("");
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vis.setBan(true);
        if (cambios == true) {
            gestorListaCocina.cargarInventario();
        }
    }//GEN-LAST:event_formWindowClosing

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        rutaFile = gestorListaCocina.abrirImagen();
        gestorListaCocina.visualizadorImagen(lblImagen, rutaFile);
    }//GEN-LAST:event_lblImagenMouseClicked

    private void visualizarImagen() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            ven.visualizarProducto(jTable1.getValueAt(row, 0) + "", false);
        }
    }

    private void guardarProductos() {
        Producto pro;

        pro = new Producto();

        pro.setNombre(txtProducto.getText());
        pro.setContenido(Double.valueOf(txtMedida.getText()));
        pro.setPrecio(Double.valueOf(txtPrecio.getText()));
        pro.setRuta(gestorListaCocina.copiarFichero(txtProducto.getText(), rutaFile, "ImagenPoducto"));
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        obtenerProductos();

        gestorListaCocina.mensaje("Producto Guardado corretamente", "Producto", 0);
        rutaFile = "";

        txtMedida.setText("");
        txtPrecio.setText("");
        txtProducto.setText("");
        cambios = true;

    }

    private void modificar() {
        Producto pro = new Producto();
        int row = jTable1.getSelectedRow();
        Object[] prod = gestorListaCocina.getListaProducto().obtenerproducto(row);

        pro.setNombre(txtProducto.getText());
        pro.setContenido(Double.valueOf(txtMedida.getText()));
        pro.setPrecio(Double.valueOf(txtPrecio.getText()));
        pro.setCodigo(gestorListaCocina.getListaProducto().codigoProducto((String) prod[0]));

        String ru = (String) prod[4];

        if (!rutaFile.equals("") && !ru.equals(rutaFile)) {
            gestorListaCocina.eliminarFichero(ru);
            pro.setRuta(gestorListaCocina.copiarFichero(txtProducto.getText(), (String) rutaFile, "imageProducto/"));
        } else {
            pro.setRuta(ru);
        }

        rutaFile = "";
        gestorListaCocina.getListaProducto().editarProducto(pro);
        gestorListaCocina.mensaje("Productos Modificado Correctamente", "Producto", 0);
        btnAdd.setText("Guardar");
        jPanel2.setBorder(
                javax.swing.BorderFactory.createTitledBorder(
                        javax.swing.BorderFactory.createLineBorder(
                                new java.awt.Color(98, 50, 35)), "Añadir Producto",
                        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                        javax.swing.border.TitledBorder.DEFAULT_POSITION,
                        new java.awt.Font("Dialog", 1, 12),
                        new java.awt.Color(98, 50, 35)
                )
        );

        ban = false;
        jTable1.setEnabled(true);
        btnCancelar.setBackground(new Color(102, 204, 255));
        btnCancelar.setForeground(new Color(98, 50, 35));
        btnCancelar.setText("Limpiar");
        txtMedida.setText("");
        txtPrecio.setText("");
        txtProducto.setText("");
        obtenerProductos();
        cambios = true;
    }

    public void obtenerProductos() {
        jTable1.setModel(gestorListaCocina.obtenerListaProducto(jTable1));
    }

    public void oservador(Observer ven, Usuario user) {
        vis.addObserver(ven);
        cambios = false;
        venConfirmeContraseña.setUsuario(user, this);
    }

    private void editarProducto() {
        int row = jTable1.getSelectedRow();
        Object[] pro = gestorListaCocina.getListaProducto().obtenerproducto(row);

        jPanel2.setBorder(
                javax.swing.BorderFactory.createTitledBorder(
                        javax.swing.BorderFactory.createLineBorder(
                                new java.awt.Color(98, 50, 35)), "Modificar Producto",
                        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                        javax.swing.border.TitledBorder.DEFAULT_POSITION,
                        new java.awt.Font("Dialog", 1, 12),
                        new java.awt.Color(98, 50, 35)
                )
        );

        txtMedida.setText(pro[1] + "");
        txtPrecio.setText(pro[2] + "");
        txtProducto.setText(pro[0] + "");
        btnCancelar.setText("Cancelar");
        btnCancelar.setBackground(new Color(255, 153, 153));
        btnCancelar.setForeground(new Color(98, 50, 35));

        String ru = pro[4] + "";
        rutaFile = ru;
        gestorListaCocina.visualizadorImagen(lblImagen, ru);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean) {

            if ((boolean) arg == true) {
                if (removerAll != true) {
                    int row = jTable1.getSelectedRow();
                    if (jTable1.getSelectedRowCount() > 0) {
                        gestorListaCocina.getListaProducto().eliminarProducto(jTable1.getModel().getValueAt(row, 0) + "");
                        gestorListaCocina.mensaje("Producto removido correctamente", "Remover producto", 1);
                        obtenerProductos();
                        cambios = true;
                    }
                } else {
                    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.setRowCount(0);
                    jTable1.setModel(modelo);
                    gestorListaCocina.getListaProducto().eliminarAllProducto();
                    gestorListaCocina.mensaje("Productos removidos correctamente", "Remover producto", 1);
                    removerAll = false;
                }

            }

        }
    }

    public void pruebaProducto() {
        Producto pro;

        pro = new Producto();
        pro.setNombre("Chantilly DG");
        pro.setContenido(1000);
        pro.setPrecio(16000);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Crema leche");
        pro.setContenido(900);
        pro.setPrecio(18400);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Lechera");
        pro.setContenido(320);
        pro.setPrecio(8550);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);
        pro = new Producto();
        pro.setNombre("Leche entera");
        pro.setContenido(900);
        pro.setPrecio(3250);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Huevo");
        pro.setContenido(30);
        pro.setPrecio(16000);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Esencia");
        pro.setContenido(90);
        pro.setPrecio(1800);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Harina");
        pro.setContenido(500);
        pro.setPrecio(2200);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);
        pro = new Producto();
        pro.setNombre("Azucar");
        pro.setContenido(1000);
        pro.setPrecio(5000);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Chocolate");
        pro.setContenido(250);
        pro.setPrecio(6500);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Hy-vol");
        pro.setContenido(1000);
        pro.setPrecio(61700);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Azucar pulverizada");
        pro.setContenido(500);
        pro.setPrecio(4100);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Bicarbonato");
        pro.setContenido(125);
        pro.setPrecio(2000);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Agua");
        pro.setContenido(6000);
        pro.setPrecio(2500);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Margarina DG");
        pro.setContenido(500);
        pro.setPrecio(5200);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Yogurt");
        pro.setContenido(150);
        pro.setPrecio(2300);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Leche en polvo");
        pro.setContenido(500);
        pro.setPrecio(6000);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Cocoa");
        pro.setContenido(250);
        pro.setPrecio(5500);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Fecula");
        pro.setContenido(90);
        pro.setPrecio(2410);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Levadura");
        pro.setContenido(7);
        pro.setPrecio(900);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Manteca");
        pro.setContenido(250);
        pro.setPrecio(2500);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

        pro = new Producto();
        pro.setNombre("Sal");
        pro.setContenido(500);
        pro.setPrecio(500);
        pro.setRuta("");
        gestorListaCocina.getListaProducto().agregarProducto(pro);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenuItem minEditar;
    private javax.swing.JMenuItem minRem;
    private javax.swing.JMenuItem minRemAll;
    private javax.swing.JPopupMenu popumenu;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

}
