/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.Cocina;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

/**
 *
 * @author USER
 */
public class VentanaPedido extends javax.swing.JFrame implements Observer {

    private Cocina gestorListaCocina;
    private String rutaImagen;
    private boolean vent;
    private Vista vis;
    private VentanaRegistrarPedido ventanaRP;
    private VentanaReporte ventanaR;
    private boolean cambios;
    private ArrayList<Integer> listaCodigo;
    private VentanaVisualisarPedido visualizarPedido;
    private ventanaConfirmeContraseña venConfirmeContraseña;
    private boolean removerAll;

    /**
     * Creates new form VentanaVentas
     */
    public VentanaPedido() {
        initComponents();
        rutaImagen = "";
        vent = false;
        vis = new Vista();
        ventanaRP = new VentanaRegistrarPedido();
        ventanaR = new VentanaReporte(this, false);
        cambios = false;
        visualizarPedido = new VentanaVisualisarPedido(this, true);
        venConfirmeContraseña = new ventanaConfirmeContraseña(this, true);
        removerAll = false;
    }

    public void setGestorListaCocina(Cocina gestorListaCocina) {
        this.gestorListaCocina = gestorListaCocina;
        setIconImage(gestorListaCocina.Icono());
        ventanaRP.setGestorListaCocina(gestorListaCocina);
        ventanaR.setGestorListaCocina(gestorListaCocina);
        visualizarPedido.setGestorListaCocina(gestorListaCocina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmeTbl = new javax.swing.JPopupMenu();
        minRem = new javax.swing.JMenuItem();
        minRemAll = new javax.swing.JMenuItem();
        minEstado = new javax.swing.JMenu();
        rbtEntrega = new javax.swing.JRadioButtonMenuItem();
        rbtPendiente = new javax.swing.JRadioButtonMenuItem();
        minReporte = new javax.swing.JMenuItem();
        minEditar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaPanel = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblGanancia = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblGasto = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        pmeTbl.setLabel("Opcion:");

        minRem.setText("Remover");
        minRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemActionPerformed(evt);
            }
        });
        pmeTbl.add(minRem);

        minRemAll.setText("Remover todo");
        minRemAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRemAllActionPerformed(evt);
            }
        });
        pmeTbl.add(minRemAll);

        minEstado.setText("Estado");

        rbtEntrega.setText("Entregado");
        rbtEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEntregaActionPerformed(evt);
            }
        });
        minEstado.add(rbtEntrega);

        rbtPendiente.setSelected(true);
        rbtPendiente.setText("Pendiente");
        rbtPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPendienteActionPerformed(evt);
            }
        });
        minEstado.add(rbtPendiente);

        pmeTbl.add(minEstado);

        minReporte.setText("Reporte");
        minReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minReporteActionPerformed(evt);
            }
        });
        pmeTbl.add(minReporte);

        minEditar.setText("Editar");
        minEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minEditarActionPerformed(evt);
            }
        });
        pmeTbl.add(minEditar);

        setTitle("Pedidos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 191, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaPanel.setEditable(false);
        txaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(98, 50, 35)), "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(98, 50, 35))); // NOI18N
        txaPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txaPanel.setForeground(new java.awt.Color(98, 50, 35));
        txaPanel.setSelectedTextColor(new java.awt.Color(255, 191, 154));
        txaPanel.setSelectionColor(new java.awt.Color(98, 50, 35));
        jScrollPane2.setViewportView(txaPanel);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 420, 200));

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(98, 50, 35));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Receta", "Cantidad", "Entrega", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setComponentPopupMenu(pmeTbl);
        jTable1.setSelectionBackground(new java.awt.Color(98, 50, 35));
        jTable1.setSelectionForeground(new java.awt.Color(255, 191, 154));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(130);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 200));

        lblImage.setForeground(new java.awt.Color(98, 50, 35));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 200, 200));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 50, 35), 1, true), "Valor $$$", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(98, 50, 35))); // NOI18N

        lblGanancia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGanancia.setForeground(new java.awt.Color(98, 50, 35));
        lblGanancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGanancia.setText("Ganancia:");

        lblPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(98, 50, 35));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio Venta: ");

        lblGasto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGasto.setForeground(new java.awt.Color(98, 50, 35));
        lblGasto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGasto.setText("Gasto total: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGasto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGanancia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblGasto)
                .addGap(19, 19, 19)
                .addComponent(lblPrecio)
                .addGap(19, 19, 19)
                .addComponent(lblGanancia)
                .addGap(59, 59, 59))
        );

        lblGanancia.getAccessibleContext().setAccessibleName("");
        lblPrecio.getAccessibleContext().setAccessibleName("");
        lblGasto.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 290, 200));

        btnCerrar.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(98, 50, 35));
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 84, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imgFondoPed.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        setVisible(false);
        if (cambios == true) {
            gestorListaCocina.cargarInventario();
        }
        vis.setBan(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (evt.getButton() == 3) {
            pmeTbl.show(jTable1, evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) {
            visualizarPedido.visualizarPedido(listaCodigo.get(row));
            visualizarPedido.setVisible(true);
        } else {
            obtenerDatos();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void minRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemActionPerformed
        int not = gestorListaCocina.mensajeConfirmar("¿Seguro que quieres eliminar este pedido?", "Comfirmar eliminacion");
        if (not == 0) {
            venConfirmeContraseña.setVisible(true);
        }
    }//GEN-LAST:event_minRemActionPerformed

    private void minRemAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRemAllActionPerformed
        int not = gestorListaCocina.mensajeConfirmar("Seguro que quieres eliminar todos los pedidos", "Comfirmar eliminacion");
        if (not == 0) {
            removerAll = true;
            venConfirmeContraseña.setVisible(true);
        }

    }//GEN-LAST:event_minRemAllActionPerformed

    private void rbtEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEntregaActionPerformed
        if (rbtEntrega.isSelected() == true) {
            rbtPendiente.setSelected(false);
            cambiarEstado(true);
        } else {
            rbtPendiente.setSelected(true);
            cambiarEstado(false);
        }
    }//GEN-LAST:event_rbtEntregaActionPerformed

    private void rbtPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPendienteActionPerformed
        if (rbtPendiente.isSelected() == true) {
            rbtEntrega.setSelected(false);
            cambiarEstado(false);
        } else {
            rbtEntrega.setSelected(true);
            cambiarEstado(true);
        }
    }//GEN-LAST:event_rbtPendienteActionPerformed

    private void minReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minReporteActionPerformed
        int row = jTable1.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        if (row >= 0) {
            ventanaR.setVisible(true);

            String med = (modelo.getValueAt(row, 2) + "").replace(".", "");
            med = med.replace(",", ".");
            System.out.println("cant: " + med);
            ventanaR.obtnerReporte(modelo.getValueAt(row, 1) + "", Double.valueOf(med), "", row);
        }

    }//GEN-LAST:event_minReporteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (cambios == true) {
            gestorListaCocina.cargarInventario();
        }
        vis.setBan(true);
    }//GEN-LAST:event_formWindowClosing

    private void minEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minEditarActionPerformed
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            ventanaRP.llenarcbx(this);
            ventanaRP.editarVenta(row);
            ventanaRP.setVisible(true);
            setVisible(false);
            vent = true;
            cambios = true;
        }
    }//GEN-LAST:event_minEditarActionPerformed

    private void cambiarEstado(boolean estado) {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            gestorListaCocina.getListaPedido().cambiarEstado(row, estado);
            cambios = true;
            llenarTabla();
        }
    }

    public void llenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        listaCodigo = new ArrayList();

        ArrayList<Object[]> ped = gestorListaCocina.obtenerTablaVentas();

        ped.stream().forEach(pedido -> {
            listaCodigo.add((int) pedido[6]);
            modelo.addRow(pedido);
        });

        jTable1.setModel(modelo);
    }

    public void Observer(Observer ven, Usuario user) {
        vis.addObserver(ven);
        cambios = false;
        venConfirmeContraseña.setUsuario(user, this);
    }

    private void obtenerDatos() {
        int row = jTable1.getSelectedRow();
        Object[] ven = gestorListaCocina.obtenerDatosVenta(row);

        lblGasto.setText("Gasto total: " + ven[0]);
        lblPrecio.setText("Precio Pedido: " + ven[1]);
        lblGanancia.setText("Ganancia: " + ven[2]);
        txaPanel.setText(ven[3] + "");
        gestorListaCocina.formatoJtexPanel(txaPanel);
        rutaImagen = (String) ven[4];
        lblImage = gestorListaCocina.visualizadorImagen(lblImage, rutaImagen);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean && vent == true) {
            setVisible(true);
            llenarTabla();
            vent = false;
        }

        if ((boolean) arg == true && vent == false) {
            if (removerAll != true) {
                int row = jTable1.getSelectedRow();
                if (jTable1.getSelectedRowCount() > 0) {
                    gestorListaCocina.getListaPedido().eliminarVenta(row);
                    gestorListaCocina.mensaje("Pedido removido correctamente", "Remover producto", 1);
                    listaCodigo.remove(row);
                    cambios = true;
                    llenarTabla();
                }
            } else {
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                modelo.setRowCount(0);
                jTable1.setModel(modelo);
                gestorListaCocina.getListaPedido().eliminarAllVenta();
                gestorListaCocina.mensaje("Pedidos removidos correctamente", "Remover producto", 1);
                listaCodigo.removeAll(listaCodigo);
                cambios = true;
                llenarTabla();
                removerAll = false;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGanancia;
    private javax.swing.JLabel lblGasto;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JMenuItem minEditar;
    private javax.swing.JMenu minEstado;
    private javax.swing.JMenuItem minRem;
    private javax.swing.JMenuItem minRemAll;
    private javax.swing.JMenuItem minReporte;
    private javax.swing.JPopupMenu pmeTbl;
    private javax.swing.JRadioButtonMenuItem rbtEntrega;
    private javax.swing.JRadioButtonMenuItem rbtPendiente;
    private javax.swing.JTextPane txaPanel;
    // End of variables declaration//GEN-END:variables

}
