/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Componente.Vista;
import controller.ListaUsuario;
import java.util.Observable;
import java.util.Observer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import model.Usuario;

/**
 *
 * @author USER
 */
public class VentanaRegistrarUsuario extends javax.swing.JFrame implements Observer{

    private ListaUsuario gestorListaUsuario;
    private String rutaImagen;
    private boolean ban;
    private Vista vis;
    private VentanaAvatar venAvatar;
    private String rutaAvatar;
    

    /**
     * Creates new form VentanaPerfil
     */
    public VentanaRegistrarUsuario() {
        initComponents();
        rutaImagen = "";
        ban = false;
        vis = new Vista();
        venAvatar = new VentanaAvatar();
    }

    public void setGestorListaUsuario(ListaUsuario gestorListaUsuario) {
        this.gestorListaUsuario = gestorListaUsuario;
        setIconImage(gestorListaUsuario.Icono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmeImage = new javax.swing.JPopupMenu();
        minAvaatar = new javax.swing.JMenuItem();
        minArchivo = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNegocio = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        tpwContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        tpwConfContraseña = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        minAvaatar.setText("Selecionar Avatar");
        minAvaatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minAvaatarActionPerformed(evt);
            }
        });
        pmeImage.add(minAvaatar);

        minArchivo.setText("Desde Archivos");
        minArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minArchivoActionPerformed(evt);
            }
        });
        pmeImage.add(minArchivo);

        setTitle("Registro Usuario");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(85, 35, 14));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 35, 14));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 35, 14));
        jLabel2.setText("Empresa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 145, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 35, 14));
        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 35, 14));
        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 338, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 35, 14));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 271, -1, -1));

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(85, 35, 14));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 189, -1));

        txtNegocio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNegocio.setForeground(new java.awt.Color(85, 35, 14));
        jPanel1.add(txtNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 165, 189, -1));

        txtCorreo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(85, 35, 14));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 290, 189, -1));

        txtUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(85, 35, 14));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 355, 189, -1));

        tpwContraseña.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tpwContraseña.setForeground(new java.awt.Color(85, 35, 14));
        tpwContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpwContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(tpwContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 293, 189, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 35, 14));
        jLabel6.setText("Comfirmar Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 335, -1, -1));

        tpwConfContraseña.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tpwConfContraseña.setForeground(new java.awt.Color(85, 35, 14));
        tpwConfContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpwConfContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(tpwConfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 357, 189, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pasteli3.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 280, 170));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chocoPastel.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 460));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(85, 35, 14));
        jLabel8.setText("Celular:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 210, -1, -1));

        txtCelular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(85, 35, 14));
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 228, 190, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/choco4.png"))); // NOI18N
        jLabel11.setText("jLabel10");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 140));

        lblImagen.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(85, 35, 14));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("Click para selecionar imagen");
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, 150));

        btnCancelar.setBackground(new java.awt.Color(85, 35, 14));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 174, 200));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(85, 35, 14));
        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 174, 200));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fondoUsuario.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        gestorListaUsuario.consumir(evt);
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        gestorListaUsuario.consumirSinEspacio(evt);
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void tpwContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpwContraseñaKeyTyped
        gestorListaUsuario.consumirSinEspacio(evt);
    }//GEN-LAST:event_tpwContraseñaKeyTyped

    private void tpwConfContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpwConfContraseñaKeyTyped
        gestorListaUsuario.consumirSinEspacio(evt);
    }//GEN-LAST:event_tpwConfContraseñaKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String mensaje = validarCampos();
        if (mensaje.equals("")) {
            registrarUsuario();
        } else {
            gestorListaUsuario.mensaje(mensaje, "Usuario",3);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        gestorListaUsuario.consumirSinEspacio(evt);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        pmeImage.show(lblImagen, evt.getX(), evt.getY());


    }//GEN-LAST:event_lblImagenMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vis.setBan(true);
    }//GEN-LAST:event_formWindowClosing

    private void minAvaatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minAvaatarActionPerformed
        venAvatar.datos(this);
        venAvatar.setVisible(true);
    }//GEN-LAST:event_minAvaatarActionPerformed

    private void minArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minArchivoActionPerformed
        rutaImagen = gestorListaUsuario.abrirImagen();
        lblImagen = gestorListaUsuario.visualizadorImagen2(lblImagen, rutaImagen);
    }//GEN-LAST:event_minArchivoActionPerformed

    private String validarCampos() {

        if (txtNombre.getText().equals("")) {
            return "El campo Nombre es obligatorio";
        }

        if (txtNegocio.getText().equals("")) {
            return "El campo Apellido es obligatorio";
        }

        if (txtUsuario.getText().equals("")) {
            return "El campo Usuario es obligatorio";
        }

        if (txtCorreo.getText().equals("")) {
            return "El campo Correo es obligatorio";
        } else {
            Pattern pattern = Pattern
                    .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

            // El email a validar
            String email = txtCorreo.getText();

            Matcher mather = pattern.matcher(email);

            if (mather.find() != true) {
                return "El email ingresado es inválido.";
            }
        }

        if (txtCelular.getText().equals("")) {
            return "El campo Celular es obligatorio";
        }

        String cont = "";
        String cont1 = "";

        if (tpwContraseña.getPassword().length < 8) {
            return "La contraseña debe tener como minimo 8 carater o digitos";
        }

        for (int i = 0; i < tpwContraseña.getPassword().length; i++) {
            cont += tpwContraseña.getPassword()[i];
        }

        for (int i = 0; i < tpwConfContraseña.getPassword().length; i++) {
            cont1 += tpwConfContraseña.getPassword()[i];
        }

        if (cont.equals("")) {
            return "El campo Contraseñaes obligatorio";
        } else if (cont1.equals("")) {
            return "El campo confirmar Contraseñaes obligatorio";
        } else if (!cont.equals(cont1)) {
            return "Las Contraseña deben coincidir";
        }

        return "";
    }

    private void registrarUsuario() {
        Usuario usuario = new Usuario();

        String cont = "";

        for (int i = 0; i < tpwContraseña.getPassword().length; i++) {
            cont += tpwContraseña.getPassword()[i];
        }

        usuario.setNombre(txtNombre.getText());
        usuario.setNegocio(txtNegocio.getText());
        usuario.setUsuario(txtUsuario.getText());
        usuario.setCelular(txtCelular.getText());
        usuario.setCorreo(txtCorreo.getText());
        usuario.setContraseña(cont);
        usuario.setRutaImagen(rutaImagen);

        if (ban == false) {
            gestorListaUsuario.crearDirectorio(txtUsuario.getText());
            usuario.setArchivo(gestorListaUsuario.getRutaArchivo() + txtUsuario.getText() + "/Archivo");
            usuario.setRutaArchivos(gestorListaUsuario.getRutaArchivo() + txtUsuario.getText() + "/");
            gestorListaUsuario.agregarUsuario(usuario);
            gestorListaUsuario.mensaje("Usuario guardado correctamente", "Usuario",0);
        } else {
            gestorListaUsuario.modificarUsuario(usuario);
            gestorListaUsuario.mensaje("Usuario modificado correctamente", "Usuario",0);
        }

        setVisible(false);
        vis.setBan(true);
    }

    public void observer(Observer ven) {
        vis.addObserver(ven);
    }

    public void modificarUsuario(Usuario user) {
        setTitle("Modificar Usuario");
        txtNombre.setText(user.getNombre());
        txtNegocio.setText(user.getNegocio());
        txtUsuario.setText(user.getUsuario());
        txtCelular.setText(user.getCelular());
        txtCorreo.setText(user.getCorreo());
        rutaImagen = user.getRutaImagen();
        tpwContraseña.setText(user.getContraseña());
        txtUsuario.setEditable(false);
        ban = true;
        lblImagen = gestorListaUsuario.visualizadorImagen(lblImagen, user.getRutaImagen());

    }
    
    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof Boolean) {
            setVisible(true);
        } else if (arg instanceof String) {
            rutaAvatar = (String) arg;
            gestorListaUsuario.visualizadorImagen2(lblImagen, rutaAvatar);
            rutaImagen = rutaAvatar;
            setVisible(true);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenuItem minArchivo;
    private javax.swing.JMenuItem minAvaatar;
    private javax.swing.JPopupMenu pmeImage;
    private javax.swing.JPasswordField tpwConfContraseña;
    private javax.swing.JPasswordField tpwContraseña;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNegocio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
