/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaInstalacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInstalacion
     */
    public VentanaInstalacion() {
        initComponents();
        System.out.println(getClass().getProtectionDomain().getCodeSource().getLocation().getPath());
//        guardarFichero("C:/Users/USER/Videos/");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        chxCondiciones = new javax.swing.JCheckBox();
        lblIconno = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnInstalar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tentacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane1.setText("Tentacion en una app para guardar recetas, hecha con fines \neducativos por lo tanto no somos responsables su mal uso\n\nSi esta de acuerdo acepte ");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 247, 400, 80));

        chxCondiciones.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        chxCondiciones.setForeground(new java.awt.Color(0, 0, 0));
        chxCondiciones.setText("Aceptar terminos y condiciones");
        chxCondiciones.setToolTipText("");
        chxCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxCondicionesActionPerformed(evt);
            }
        });
        jPanel1.add(chxCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, -1));

        lblIconno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/portada.png"))); // NOI18N
        jPanel1.add(lblIconno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, 130));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        btnInstalar.setBackground(new java.awt.Color(51, 204, 0));
        btnInstalar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnInstalar.setForeground(new java.awt.Color(255, 255, 255));
        btnInstalar.setText("Instalar");
        btnInstalar.setEnabled(false);
        btnInstalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstalarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInstalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 80, -1));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/My project-1 (1).png"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void chxCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxCondicionesActionPerformed
        if (chxCondiciones.isSelected()) {
            btnInstalar.setEnabled(true);
        } else {
            btnInstalar.setEnabled(false);
        }
    }//GEN-LAST:event_chxCondicionesActionPerformed

    private void btnInstalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstalarActionPerformed
        JFileChooser jfile = new JFileChooser();
        jfile.setDialogTitle("Instalar en");
        jfile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Component parent = null;
        int returnVal = jfile.showSaveDialog(parent);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String selectPath = jfile.getSelectedFile().getPath();
//            System.out.println("El directorio que elija es:" + selectPath);
            guardarFichero(selectPath);
        }
        
    }//GEN-LAST:event_btnInstalarActionPerformed

    public void guardarFichero(String rutaInstalar) {

        String ruta = getClass().getProtectionDomain().getCodeSource().getLocation().getPath();
        System.out.println("");
        String[] ru = ruta.split("/");
        ruta = "";
        for (int i = 1; i < ru.length - 1; i++) {
            ruta = ruta + ru[i]+ "/" ;
        }
//        ruta = ruta + "dist/";
//        ruta = "C:/Users/USER/Documents/NetBeansProjects/ProyectoInstalacion/dist/";
        String rut = ruta;
        Path sourcePath;
        Path targetPath;
        System.out.println(ruta);

        String[] img = new String[]{"prueba1.jpg", "prueba2.jpg", "prueba3.jpg", "prueba4.jpeg"};

        for (int i = 0; i < img.length; i++) {
            ruta = ruta + img[i];
            System.out.println(ruta);

            sourcePath = Paths.get(ruta);
            targetPath = Paths.get(rutaInstalar+"/"+img[i]);


            try {
                Files.copy(sourcePath, targetPath);
            } catch (FileAlreadyExistsException ex) {
                JOptionPane.showMessageDialog(null,"The target path already has a target file");
            } catch (IOException exception) {
                JOptionPane.showMessageDialog(null,"I/O error: "+ exception);
            }
            
            ruta = rut;
        }
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInstalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInstalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInstalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInstalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInstalacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInstalar;
    private javax.swing.JCheckBox chxCondiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblIconno;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
