/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;

public class VentanaDivisasCliente extends javax.swing.JFrame implements Observer {

    private String nombreProductoActual;
    

    public VentanaDivisasCliente() {
        initComponents();
        Cliente c = new Cliente(5000);
        c.addObserver(this);
        Thread t = new Thread(c);
        t.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDolar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEuro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLibra = new javax.swing.JTextField();
        txtRublo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtYen = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon2.png")).getImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dolar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 40, -1, -1));

        txtDolar.setEditable(false);
        txtDolar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Euro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 80, -1, -1));

        txtEuro.setEditable(false);
        txtEuro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtEuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Libra Esterlina:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtLibra.setEditable(false);
        txtLibra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtLibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, -1));

        txtRublo.setEditable(false);
        txtRublo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtRublo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rublo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Yen:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        txtYen.setEditable(false);
        txtYen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtYen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoCliente.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
//            System.out.println(com.jtattoo.plaf.acryl.AcrylLookAndFeel.getThemes().get(10).toString());
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme(com.jtattoo.plaf.acryl.AcrylLookAndFeel.getThemes().get(10).toString());
           javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDivisasCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtDolar;
    private javax.swing.JTextField txtEuro;
    private javax.swing.JTextField txtLibra;
    private javax.swing.JTextField txtRublo;
    private javax.swing.JTextField txtYen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {

        if (arg instanceof String) {
            nombreProductoActual = (String) arg;
        } else {

            double valor = (double) arg;
            switch (nombreProductoActual) {
                case "Dolar":
                    this.txtDolar.setText(valor + "");
                    break;
                case "Euro":
                    this.txtEuro.setText(valor + "");
                    break;
                case "Libra":
                    this.txtLibra.setText(valor + "");
                    break;
                case "Rublo":
                    this.txtRublo.setText(valor + "");
                    break;
                case "Yen":
                    this.txtYen.setText(valor + "");
                    break;
            }

        }

    }

}
