/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VentanaDivisasServidor extends javax.swing.JFrame {

    private Servidor s;
    private Servidor_1 s2;

    public VentanaDivisasServidor() {
        initComponents();
        s = new Servidor(5000);
        Thread t = new Thread(s);
        t.start();

        s2 = new Servidor_1();
        Thread tt = new Thread(s2);
        tt.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDolar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEuro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLibra = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        txtRublo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtYen = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dolar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txtDolar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDolarKeyTyped(evt);
            }
        });
        jPanel1.add(txtDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 183, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Euro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        txtEuro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEuroKeyTyped(evt);
            }
        });
        jPanel1.add(txtEuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 183, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Libra Esterlina:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtLibra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLibra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibraKeyTyped(evt);
            }
        });
        jPanel1.add(txtLibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 183, -1));

        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar Divisas");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 287, -1));

        txtRublo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRublo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRubloKeyTyped(evt);
            }
        });
        jPanel1.add(txtRublo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 183, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rublo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Yen:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 220, -1, -1));

        txtYen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtYen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYenKeyTyped(evt);
            }
        });
        jPanel1.add(txtYen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 183, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoServidor.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        ErroresFormulario errores = new ErroresFormulario();

        errores.validarNumeroReal(this.txtDolar.getText());
        errores.validarNumeroReal(this.txtEuro.getText());
        errores.validarNumeroReal(this.txtLibra.getText());
        errores.validarNumeroReal(this.txtRublo.getText());
        errores.validarNumeroReal(this.txtYen.getText());

        if (!errores.hasError()) {

            double dolar = Double.parseDouble(this.txtDolar.getText());
            double euro = Double.parseDouble(this.txtEuro.getText());
            double libra = Double.parseDouble(this.txtLibra.getText());
            double rublo = Double.parseDouble(this.txtRublo.getText());
            double yen = Double.parseDouble(this.txtYen.getText());

            String[] nombres = {"Dolar", "Euro", "Libra", "Rublo", "Yen"};
            double[] valores = {dolar, euro, libra, rublo, yen};

            s.enviarInfo(nombres, valores);

        } else {
            JOptionPane.showMessageDialog(this, errores.getErrores(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtDolarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDolarKeyTyped
        txtDolar.setText(consume(evt,txtDolar.getText()));
    }//GEN-LAST:event_txtDolarKeyTyped

    private void txtEuroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEuroKeyTyped
        txtEuro.setText(consume(evt,txtEuro.getText()));
    }//GEN-LAST:event_txtEuroKeyTyped

    private void txtLibraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibraKeyTyped
        txtLibra.setText(consume(evt,txtLibra.getText()));
    }//GEN-LAST:event_txtLibraKeyTyped

    private void txtRubloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRubloKeyTyped
        txtRublo.setText(consume(evt,txtRublo.getText()));
    }//GEN-LAST:event_txtRubloKeyTyped

    private void txtYenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYenKeyTyped
       txtYen.setText(consume(evt,txtYen.getText()));
    }//GEN-LAST:event_txtYenKeyTyped

    private String consume(KeyEvent evt, String txt) {
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros && key != 44) {
            evt.consume();
        }

        if (key == 44) {
            for (int i = 0; i < txt.length() - 1; i++) {
                if (txt.charAt(i) == ',') {
                    evt.consume();
                }
            }
        }
        return txt;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisasServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDivisasServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtDolar;
    private javax.swing.JTextField txtEuro;
    private javax.swing.JTextField txtLibra;
    private javax.swing.JTextField txtRublo;
    private javax.swing.JTextField txtYen;
    // End of variables declaration//GEN-END:variables

}
