/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Resultado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Ecuacion;

/**
 *
 * @author USER
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private boolean ban;
    private int indVar;
    private int numVariable;
    ArrayList<Ecuacion> restrinciones;
    Ecuacion funcion;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        ban = false;
        indVar = 0;
        numVariable = 0;
        btnMayor.setEnabled(false);
        btnmenor.setEnabled(false);
        btnIgual.setEnabled(false);
        txtRestrin.setEnabled(false);
        btnIniciar.setEnabled(false);
        btnAgregar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFuncion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRestrin = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaResultados = new javax.swing.JTextArea();
        btnValidar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jrbProceso = new javax.swing.JRadioButton();
        lblValidar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnmenor = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnRetro = new javax.swing.JButton();
        btnXn = new javax.swing.JButton();
        rbtMin = new javax.swing.JRadioButton();
        rbtMax = new javax.swing.JRadioButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maximimzar y Minimizar");
        setBackground(new java.awt.Color(0, 21, 36));

        jPanel1.setBackground(new java.awt.Color(120, 41, 15));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtFuncion.setEditable(false);
        txtFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFuncionMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Restrinciones:");

        txtRestrin.setEditable(false);
        txtRestrin.setEnabled(false);
        txtRestrin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRestrinMouseClicked(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(21, 97, 109));
        btnAgregar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Resultado:");

        txaResultados.setEditable(false);
        txaResultados.setBackground(new java.awt.Color(255, 255, 255));
        txaResultados.setColumns(20);
        txaResultados.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txaResultados.setForeground(new java.awt.Color(0, 0, 0));
        txaResultados.setRows(5);
        jScrollPane2.setViewportView(txaResultados);

        btnValidar.setBackground(new java.awt.Color(21, 97, 109));
        btnValidar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Funcion Objetivo:");

        jrbProceso.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jrbProceso.setForeground(new java.awt.Color(255, 255, 255));
        jrbProceso.setSelected(true);
        jrbProceso.setText("Mostrar procesos");

        lblValidar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        lblValidar.setForeground(new java.awt.Color(153, 255, 0));
        lblValidar.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                            .addComponent(jrbProceso))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRestrin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnValidar))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRestrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrbProceso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel2.setBackground(new java.awt.Color(255, 125, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn1.setBackground(new java.awt.Color(120, 41, 0));
        btn1.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(120, 41, 0));
        btn2.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(120, 41, 0));
        btn3.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(120, 41, 0));
        btn4.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(120, 41, 0));
        btn5.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(120, 41, 0));
        btn6.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(120, 41, 0));
        btn7.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(120, 41, 0));
        btn8.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(120, 41, 0));
        btn9.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(120, 41, 0));
        btn0.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnMas.setBackground(new java.awt.Color(120, 41, 0));
        btnMas.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btnMas.setForeground(new java.awt.Color(255, 255, 255));
        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(120, 41, 0));
        btnMenos.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(120, 41, 0));
        btnPunto.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(255, 255, 255));
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(120, 41, 0));
        btnIgual.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnmenor.setBackground(new java.awt.Color(120, 41, 0));
        btnmenor.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btnmenor.setForeground(new java.awt.Color(255, 255, 255));
        btnmenor.setText("<");
        btnmenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenorActionPerformed(evt);
            }
        });

        btnMayor.setBackground(new java.awt.Color(120, 41, 0));
        btnMayor.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        btnMayor.setForeground(new java.awt.Color(255, 255, 255));
        btnMayor.setText(">");
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });

        btnRetro.setBackground(new java.awt.Color(120, 41, 0));
        btnRetro.setFont(new java.awt.Font("Doppio One", 1, 10)); // NOI18N
        btnRetro.setForeground(new java.awt.Color(255, 255, 255));
        btnRetro.setText("<--");
        btnRetro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetroMouseClicked(evt);
            }
        });

        btnXn.setBackground(new java.awt.Color(120, 41, 0));
        btnXn.setFont(new java.awt.Font("Doppio One", 1, 12)); // NOI18N
        btnXn.setForeground(new java.awt.Color(255, 255, 255));
        btnXn.setText("Xn");
        btnXn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXnActionPerformed(evt);
            }
        });

        rbtMin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtMin.setForeground(new java.awt.Color(120, 41, 15));
        rbtMin.setSelected(true);
        rbtMin.setText("Min");
        rbtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMinActionPerformed(evt);
            }
        });

        rbtMax.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtMax.setForeground(new java.awt.Color(120, 41, 15));
        rbtMax.setText("Max");
        rbtMax.setToolTipText("");
        rbtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMaxActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 21, 36));
        btnLimpiar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar ");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(120, 41, 15));
        btnCerrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(21, 97, 109));
        btnIniciar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtMax))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRetro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXn))
                            .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMin)
                    .addComponent(rbtMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        ingreasarTexto("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void txtFuncionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFuncionMouseClicked

        if (txtFuncion.isEnabled() == true) {
            btnMayor.setEnabled(false);
            btnmenor.setEnabled(false);
            btnIgual.setEnabled(false);
            ban = false;
        }

    }//GEN-LAST:event_txtFuncionMouseClicked

    private void txtRestrinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRestrinMouseClicked

        if (txtRestrin.isEnabled() == true) {
            btnMayor.setEnabled(true);
            btnmenor.setEnabled(true);
            btnIgual.setEnabled(true);
            ban = true;
        }

    }//GEN-LAST:event_txtRestrinMouseClicked

    private void btnRetroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetroMouseClicked

        if (ban == true) {
            txtRestrin.setText(borrar(txtRestrin.getText()));
        } else {
            txtFuncion.setText(borrar(txtFuncion.getText()));
        }
    }//GEN-LAST:event_btnRetroMouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        ingreasarTexto("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        ingreasarTexto("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        ingreasarTexto("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        ingreasarTexto("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        ingreasarTexto("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        ingreasarTexto("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        ingreasarTexto("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        ingreasarTexto("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        ingreasarTexto("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        if (buscarcaraterFinal('+') == false) {
            ingreasarTexto("+");
        }
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        if (buscarcaraterFinal('-') == false) {
            ingreasarTexto("-");
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (buscarcaraterFinal('.') == false) {
            ingreasarTexto(".");
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        if (buscarCarater('=') == false) {
            ingreasarTexto("=");
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnmenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenorActionPerformed
        if (buscarCarater('<') == false) {
            ingreasarTexto("<");
        }
    }//GEN-LAST:event_btnmenorActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        if (buscarCarater('>') == false) {
            ingreasarTexto(">");
        }
    }//GEN-LAST:event_btnMayorActionPerformed

    private boolean buscarcaraterFinal(char ch) {
        if (ban == true) {
            if (txtRestrin.getText().length() > 0 && txtRestrin.getText().charAt(txtRestrin.getText().length() - 1) == ch) {
                return true;
            }
        } else if (txtFuncion.getText().length() > 0 && txtFuncion.getText().charAt(txtFuncion.getText().length() - 1) == ch) {
            return true;
        }
        return false;
    }

    private boolean buscarCarater(char ch) {
        int tam;
        String tex;
        if (ban == true) {
            tex = txtRestrin.getText();
        } else {
            tex = txtFuncion.getText();
        }

        tam = tex.length();

        for (int i = 0; i < tam; i++) {
            if (tex.charAt(i) == ch) {
                return true;
            }
        }

        return false;
    }


    private void btnXnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXnActionPerformed
        indVar++;
        ingreasarTexto("X" + indVar);

    }//GEN-LAST:event_btnXnActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed

        if (validarEcuacion(txtFuncion.getText()) != null) {
            funcion = new Ecuacion();
            restrinciones = new ArrayList<>();
            funcion = validarEcuacion(txtFuncion.getText());
            txtRestrin.setEnabled(true);
            btnAgregar.setEnabled(true);
            numVariable = indVar;
            indVar = 0;
            ban = true;
            txtFuncion.setEnabled(false);
            txaResultados.setText("Funcion Objetivo" + "\n\n" + "\t" + txtFuncion.getText() + "\n" + "\n" + "Restrinciones " + "\n");
            btnValidar.setEnabled(false);
            lblValidar.setText("!Funcion Ingresada Corretamente¡");
            btnMayor.setEnabled(true);
            btnmenor.setEnabled(true);
            btnIgual.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, txtFuncion.getText() + "\n" + "Error de Sintaxis");
        }

    }//GEN-LAST:event_btnValidarActionPerformed


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (validarRestrincion(txtRestrin.getText()) != null) {
            restrinciones.add(validarRestrincion(txtRestrin.getText()));
            indVar = 0;
            txaResultados.setText(txaResultados.getText() + "\n" + "\t" + txtRestrin.getText());
            txtRestrin.setText("");

            if (restrinciones.size() > 1) {
                btnIniciar.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, txtRestrin.getText() + "\n" + "Error de Sintaxis");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        String texto = "\n\n\t";
        for (int i = 0; i < numVariable; i++) {
            texto = texto + "   X" + (i + 1) + ">= 0;   ";
        }
        texto = texto + "\n\n";
        txaResultados.setText(txaResultados.getText() + texto);

        Resultado resultado = new Resultado(restrinciones, funcion, rbtMax.isSelected());

        resultado.obtenerResultados();

        if (jrbProceso.isSelected() == true) {
            txaResultados.setText(txaResultados.getText() + resultado.getTexto() + "\n");
        }

    }//GEN-LAST:event_btnIniciarActionPerformed


    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtFuncion.setEnabled(true);
        txtRestrin.setEnabled(false);
        txaResultados.setText("");
        txtFuncion.setText("");
        txtRestrin.setText("");
        indVar = 0;
        numVariable = 0;
        ban = false;
        btnMayor.setEnabled(false);
        btnmenor.setEnabled(false);
        btnIgual.setEnabled(false);
        btnValidar.setEnabled(true);
        btnIniciar.setEnabled(true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void rbtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMinActionPerformed
        if (rbtMin.isSelected() == true) {
            rbtMax.setSelected(false);
        } else {
            rbtMax.setSelected(true);
        }
    }//GEN-LAST:event_rbtMinActionPerformed

    private void rbtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMaxActionPerformed
        if (rbtMax.isSelected() == true) {
            rbtMin.setSelected(false);
        } else {
            rbtMin.setSelected(true);
        }
    }//GEN-LAST:event_rbtMaxActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void ingreasarTexto(String texto) {
        if (ban == true) {
            txtRestrin.setText(txtRestrin.getText() + texto);
        } else {
            txtFuncion.setText(txtFuncion.getText() + texto);
        }
    }

    private String borrar(String texto) {
        String tex = "";
        int tam = texto.length() - 1;

        for (int i = 0; i < tam; i++) {
            tex = tex + texto.charAt(i);
        }

        if (tex.length() > 0 && tex.charAt(tex.length() - 1) == 'X') {
            tex = borrar(tex);
            indVar--;
        }

        return tex;
    }

    private Ecuacion validarEcuacion(String ecuacion) {

        Ecuacion ecua = new Ecuacion();
        String num = "";
        boolean val = true;
        int n = 1;

        if (ecuacion.charAt(0) == 'X') {
            num = "1";
        }

        if (ecuacion.charAt(ecuacion.length() - 2) == 'X') {
            for (int i = 0; i < ecuacion.length(); i++) {

                if (ecuacion.charAt(i) == 'X') {

                    val = true;
                    for (int j = 0; j < num.length(); j++) {

                        if (!(num.codePointAt(j) >= 43 && num.codePointAt(j) <= 57)) {
                            val = false;
                            break;
                        }
                    }

                    if (val == true) {
                        if ("-".equals(num)) {
                            num = "-1";
                        }
                        ecua.getX().add(Float.valueOf(num));
                    }

                    if (val == true && ecuacion.length() - i != 2) {

                        if ((ecuacion.charAt(i + 2) == '+' || ecuacion.charAt(i + 2) == '-')) {

                            i = i + 3;

                            num = "";
                            if (ecuacion.charAt(i) == 'X') {
                                num = "1";
                                i--;
                                val = false;
                            }
                        } else {

                            return null;
                        }
                    }

                }
                if (val == true) {
                    num = num + ecuacion.charAt(i);
                }

            }

        } else {

            return null;
        }

        return ecua;
    }

    private Ecuacion validarRestrincion(String ecuacion) {
        String num = "";
        Ecuacion ecua = null;

        if ((buscarCarater('<') == true || buscarCarater('>') == true) && buscarCarater('=') == true) {

            for (int i = 0; i < ecuacion.length(); i++) {
                if (ecuacion.charAt(i) == '<' || ecuacion.charAt(i) == '>') {

                    if (validarEcuacion(num) != null) {
                        ecua = validarEcuacion(num);

                        if (ecua.getX().size() != numVariable) {
                            return null;
                        }

                        num = "";
                        for (int j = (i + 2); j < ecuacion.length(); j++) {
                            if (!(ecuacion.charAt(j) >= 43 && ecuacion.charAt(j) <= 57)) {
                                return null;
                            } else {
                                num = num + ecuacion.charAt(j);
                            }
                        }
                        ecua.setSigno(ecuacion.charAt(i) + "" + ecuacion.charAt(i + 1) + "");
                        ecua.setResultado(Float.valueOf(num));
                        if (ecua.getResultado() < 0) {
                            return null;
                        }
                    } else {

                        return null;
                    }
                    break;
                }
                num = num + ecuacion.charAt(i);
            }
        } else {
            return null;
        }

        return ecua;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRetro;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnXn;
    private javax.swing.JButton btnmenor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jrbProceso;
    private javax.swing.JLabel lblValidar;
    private javax.swing.JRadioButton rbtMax;
    private javax.swing.JRadioButton rbtMin;
    private javax.swing.JTextArea txaResultados;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtRestrin;
    // End of variables declaration//GEN-END:variables
}
