/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogPedirDatos.java
 *
 * Created on 03-nov-2017, 11:30:15
 */
package proyectografolistaadya;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * 
 */
public class DialogPedirDatos extends javax.swing.JDialog implements ActionListener{
         GrafoListas grafo;
         int mat[][],N,M;
        JPanel panelLetrero,panelMatriz,panelBotones,panelTtotal;
        JLabel letrero;
        JButton btnAceptar;
        JToggleButton  matrizBotones[][];// PARA GUARDAR LA MATRIZ DE BOTONES
         public DialogPedirDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
public DialogPedirDatos(java.awt.Frame parent, boolean modal, GrafoListas grafo) {
        super(parent, modal);
        initComponents();
         setTitle("GRAFOS NO DIRIGIDOS REPRESENTADOS COMO LISTAS LIGADAS DE ADYACENCIA");
        this.grafo=grafo;
        N=grafo.obtenerNVertices();
        M=N;
        panelBotones = new JPanel();
        panelBotones.setLayout(new FlowLayout());
        panelBotones.add(jButton1);
   
        //**************************************************
        // SE CONSTRUYE PANELMATRIZ PARA GUARDAR LOS BOTONES
        // SE COLOCA EL ADMINISTRADOR GRIDLAYOUT PARA TENER
        // UNA REGILLA PARA UBICAR LOS BOTONES 
        //**************************************************
        panelMatriz= new JPanel();
        panelMatriz.setLayout(new GridLayout(N,M));
        matrizBotones = new JToggleButton[N][M];// SE CREA LA MATRIZ DE BOTONES
        for( int i = 0 ; i < N ;i++)
        {
                for ( int j=0; j <M ; j++)
                {
	// SE CONSTRUYE EL BOTON Y SE INSERTA AL PANEL
                    matrizBotones[i][j]= new JToggleButton(""+ (i+1)+ " - "+ (j+1));
                    matrizBotones[i][j].addActionListener(this);
                    panelMatriz.add(matrizBotones[i][j]);
                    if(i== j)
                    {
                        matrizBotones[i][j].setEnabled(false);
                    }
                }
        }
        panelLetrero = new JPanel();
       
        panelLetrero.setLayout(new FlowLayout());
        letrero=new JLabel("Seleccionar si del vertice i se puede ir al vertice j");
        panelLetrero.add(letrero);
         panelTtotal= new JPanel();
          panelTtotal.setLayout(new BorderLayout());
         panelTtotal.setLayout(new BorderLayout());
        panelTtotal.add("North",panelLetrero);
        panelTtotal.add("Center",panelMatriz);
        panelTtotal.add("South",panelBotones);
        
         getContentPane().setPreferredSize(new Dimension(500,400));
         getContentPane().setLayout(new FlowLayout());
       
        getContentPane().add(panelTtotal);
    
        resize(M* 50+300,35*(N+2)+50);
        show();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jButton1)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    
     for( int i = 0 ; i < N ;i++)
        {
                for ( int j=0; j <M ; j++)
                {
	if(matrizBotones[i][j].isSelected()== true)
                        {
                                grafo.insertarNodo(i, j);
                        }
                 
                }
        }
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed
 public void actionPerformed( ActionEvent e)
    {
        
         
        if( e.getSource() instanceof JToggleButton )
          {
                
              for( int i = 0 ; i < N ;i++)
            {
                for ( int j=0; j <M ; j++)
                {
	
                    if( e.getSource() == matrizBotones[i][j] )
                    {
                       
                       matrizBotones[j][i].setSelected(     matrizBotones[i][j].isSelected()  );
                    }
                }
            }
                
           }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPedirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPedirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPedirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPedirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogPedirDatos dialog = new DialogPedirDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
