/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sendmoremoney;

import org.chocosolver.solver.Model;
import org.chocosolver.solver.Solution;
import org.chocosolver.solver.Solver;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.util.tools.VariableUtils;

/**
 *
 * @author Estudiante
 */
public class multiplicacion extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public multiplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_to = new javax.swing.JLabel();
        lbl_cat = new javax.swing.JLabel();
        lbl_cat2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Solucionar = new javax.swing.JButton();
        lbl_ooso = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_tavo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_to.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_to.setText("TO");

        lbl_cat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cat.setText("CAT");

        lbl_cat2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cat2.setText("CAT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("x");

        jLabel1.setText("---------------------------------");

        btn_Solucionar.setText("Solucionar");
        btn_Solucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SolucionarActionPerformed(evt);
            }
        });

        lbl_ooso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_ooso.setText("OOSO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("+");

        jLabel2.setText("-------------------------------");

        lbl_tavo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_tavo.setText("TAVO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Solucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_cat)
                                    .addComponent(lbl_to)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_ooso)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cat2)
                    .addComponent(lbl_tavo))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_to)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tavo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lbl_cat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ooso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btn_Solucionar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SolucionarActionPerformed
        Model model = new Model("CSP Solver");

        // Variables
        IntVar C = model.intVar("C", 0, 9);
        IntVar A = model.intVar("A", 0, 9);
        IntVar T = model.intVar("T", 0, 9);
        IntVar O = model.intVar("O", 0, 0);
        IntVar S = model.intVar("S", 0, 9);
        IntVar V = model.intVar("V", 0, 9);

        // Constraints
        model.allDifferent(C, A, T, O, S, V).post();

        IntVar cat = model.intVar("CAT", 100, 999);
        IntVar to = model.intVar("TO", 10, 99);
        IntVar tavo = model.intVar("TAVO", 1000, 9999);
        IntVar ooso = model.intVar("OOSO", 1000, 9999);

        model.times(cat, to, tavo);
        tavo.add(cat);
        
        // Restricción: TAVO + CAT = OOSO
        model.arithm(tavo, "=", ooso).post();

        // Solve
        Solver solver = model.getSolver();
        solver.solve();

        // Print solution
        System.out.println("C = " + C.getValue());
        System.out.println("A = " + A.getValue());
        System.out.println("T = " + T.getValue());
        System.out.println("O = " + O.getValue());
        System.out.println("S = " + S.getValue());
        System.out.println("V = " + V.getValue());

        String catx = " " + C.getValue() + A.getValue() + T.getValue();
        String tox = "" + T.getValue() + O.getValue();
        String tavox = "" + T.getValue() + A.getValue() + V.getValue() + O.getValue();
        String oosox = " " + O.getValue() + O.getValue() + S.getValue() + O.getValue();

        lbl_cat.setText(catx);
        lbl_to.setText(tox);
        lbl_tavo.setText(tavox);
        lbl_cat2.setText(catx);
        lbl_ooso.setText(oosox);


    }//GEN-LAST:event_btn_SolucionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Solucionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_cat;
    private javax.swing.JLabel lbl_cat2;
    private javax.swing.JLabel lbl_ooso;
    private javax.swing.JLabel lbl_tavo;
    private javax.swing.JLabel lbl_to;
    // End of variables declaration//GEN-END:variables
}
